name: All-or-nothing
version: 1.3.0
api: 4.0.0
author: GamerMJay2008 and leMimic
main: AON\allornothing\Main
commands:
  aon:
    description: "All or Nothing Command"
    permission: aon.cmd
    permission-message: "You cannot use this command"

permissions:
  aon.cmd:
    default: op
